[pi-day]
title = "Celebrate Pi Day"
experiences = [ "pi", "pi-circle", "pi-walk" ]

[interactive]
title = "Interactive Experiences"
experiences = [
  "ai-artist",
  "ifs",
  "hilbert",
  "wind",
  "life",
  "stylegan",
  "style-transfer",
  "fluid",
  "pong4",
  "your-campus",
  "sorting"
]

[game]
title = "BYU Games"
experiences = [ "brawlers", "beatboxers", "neokaiju", "avastye" ]

[animation]
title = "BYU Animation"
experiences = [
  "taijitu",
  "grendel",
  "death",
  "estefan",
  "metro",
  "owned",
  "papa",
  "rams-horn",
  "salt",
  "stowaway"
]

[graduation]
title = "Graduation"
experiences = [
  "graduation",
  "photo-op"
]
