name: "build-experiences"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Echo last ref
      run: echo test ${{ github.event.pull_request.base.sha }} test
    - name: Checkout last ref
      uses: actions/checkout@v3
      path: ./last-ref
      ref: ${{ github.event.pull_request.base.sha }}
    - name: List directories
      run: ls
